# ===== LOCAL PROFILE =====
spring.datasource.url=jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=PC90JC
spring.datasource.password=Admin123
